### PR TITLE
Fix Errors in Code

### PR DESCRIPTION
**Pull request by monkxy**
I fixed the errors make sure to merge.

### CODE REVIEW

**Comment by JJ-gren** [comment]
monkey

**Review by Realswitzer — APPROVED** [review]
LGTM! Maintainer should merge ASAP.

**Review by src-ry — APPROVED** [review]
Works for me! Maintainer really needs to merge this quick before the entire world catches on fire and explodes!

**Review by microcrit — APPROVED** [review]
This improved the bookmarklet's performance, certainly fixed the crashing issues, and makes hacks bearable on a Chromebook. Please merge ASAP. This is an amazing pull, I wish stuff like this would be done for VSCode, etc.

**Comment by JJ-gren** [comment]
This sucks ass + monkey

**Pull request closed without merging**
